language: ruby
addons:
  postgresql: "9.4"
services:
  - redis-server
rvm:
  - 2.1.2
gemfile: Gemfile
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - psql -c 'create database projstud_test;' -U postgres
  - cp config/database.yml.travis  config/database.yml
  - bundle exec rackup private_pub.ru -s thin -E production &
  - sleep 3
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec