# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0adc26bac72b7760171d25230497af753b41a9d216ba0d397fae4244ad38ed2b175950efb6ed1dd67be35c0372b51207eb577ad961ed946a6d1b0f00a11ea6dc

test:
  secret_key_base: 3f7e4299a6f7da3375b6b81fd5a5c501a1ba342d7d34d1a70bd44b3399d7405ceed4240c5dcec9ee2f2cc2c31df1f7e11ef9f112b9d87ec9fc15681ebda1a1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
